import { StyleSheet } from "react-native";
import { Colors } from "@/constants/Colors";

export const getStyles = (colorScheme: 'light' | 'dark') => {
  const colors = Colors[colorScheme];
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
    },
    header: {
      backgroundColor: colors.card,
      padding: 16,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    headerTop: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    className: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
    },
    headerDateRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    dateText: {
      fontSize: 12,
      color: colors.textSecondary,
      flex: 1,
    },
    timeText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.error,
      marginLeft: 8,
    },
    searchBox: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      margin: 12,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
    },
    actionRow: {
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 12,
      marginBottom: 10,
    },
    btnPresent: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      backgroundColor: colors.success + "22",
      borderRadius: 10,
      paddingVertical: 11,
      borderWidth: 0.5,
      borderColor: colors.success + "55",
    },
    btnPresentText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.success,
    },
    btnClear: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      backgroundColor: colors.error + "22",
      borderRadius: 10,
      paddingVertical: 11,
      borderWidth: 0.5,
      borderColor: colors.error + "55",
    },
    btnClearText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.error,
    },
    card: {
      backgroundColor: colors.card,
      marginHorizontal: 12,
      marginBottom: 10,
      borderRadius: 12,
      padding: 14,
      borderWidth: 0.5,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
    },
    cardTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 12,
    },
    divider: {
      height: 0.5,
      backgroundColor: colors.border,
      marginVertical: 10,
    },
    noResult: {
      paddingVertical: 24,
      alignItems: "center",
    },
    noResultText: {
      color: colors.textSecondary,
      fontSize: 13,
    },
    studentRow: {
      flexDirection: "row",
    },
    studentName: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    studentMeta: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    statusRow: {
      flexDirection: "row",
      gap: 14,
      marginTop: 8,
      alignItems: "center",
    },
    checkItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    checkbox: {
      width: 17,
      height: 17,
      borderRadius: 4,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    checkPresent: {
      backgroundColor: colors.success,
      borderColor: colors.success,
    },
    checkAbsent: {
      backgroundColor: colors.error,
      borderColor: colors.error,
    },
    checkLate: {
      backgroundColor: colors.warning,
      borderColor: colors.warning,
    },
    checkLabel: {
      fontSize: 12,
      color: colors.text,
    },
    summaryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    summaryItem: {
      flex: 1,
      minWidth: "40%",
      backgroundColor: colors.background,
      borderRadius: 10,
      padding: 12,
      alignItems: "center",
    },
    summaryNum: {
      fontSize: 28,
      fontWeight: "700",
    },
    summaryLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    rateDivider: {
      height: 0.5,
      backgroundColor: colors.border,
      marginVertical: 12,
    },
    rateRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    rateLabel: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    rateValue: {
      fontSize: 15,
      fontWeight: "700",
    },
    saveBtn: {
      marginHorizontal: 12,
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: 15,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    saveBtnDone: {
      backgroundColor: colors.success,
    },
    saveBtnText: {
      color: "white",
      fontSize: 15,
      fontWeight: "700",
    },
    editBtn: {
      marginHorizontal: 12,
      backgroundColor: colors.warning,
      borderRadius: 12,
      paddingVertical: 15,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    editBtnText: {
      color: "white",
      fontSize: 15,
      fontWeight: "700",
    },
    calloutBox: {
      marginHorizontal: 12,
      marginBottom: 10,
      backgroundColor: colors.error + "11",
      padding: 12,
      borderRadius: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderWidth: 1,
      borderColor: colors.error + "44",
    },
    calloutText: {
      flex: 1,
      color: colors.error,
      fontSize: 13,
      fontWeight: "500",
    },
    notesInput: {
      marginTop: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.background,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      fontSize: 13,
      color: colors.text,
    },
    historyBtn: {
      marginHorizontal: 12,
      marginBottom: 10,
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    historyBtnText: {
      flex: 1,
      color: colors.primary,
      fontSize: 14,
      fontWeight: "600",
    },
    courseSelector: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    classSub: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    sessionRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 16,
    },
    sessionBtn: {
      flex: 1,
      backgroundColor: colors.background,
      paddingVertical: 10,
      borderRadius: 8,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    sessionBtnActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    sessionBtnText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
    },
    sessionBtnTextActive: {
      color: "white",
    },
    checkExcused: {
      backgroundColor: colors.warning,
      borderColor: colors.warning,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: 40,
      maxHeight: "80%",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 20,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
    },
    courseItem: {
      padding: 20,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    courseItemActive: {
      backgroundColor: colors.primary + "11",
    },
    courseItemName: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    courseItemNameActive: {
      color: colors.primary,
    },
    courseItemCode: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 4,
    },
    emptyCourses: {
      padding: 40,
      alignItems: "center",
    },
    emptyCoursesText: {
      color: colors.textSecondary,
      fontSize: 14,
    },
  });
};
