import { StyleSheet } from "react-native-unistyles";

export const stylesheet = StyleSheet.create((theme) => ({
  safe: { flex: 1, backgroundColor: theme.colors.background },
  calendarContainer: {
    backgroundColor: theme.colors.card,
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  monthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 25,
    paddingVertical: 15,
  },
  monthText: { fontSize: 18, fontWeight: "800", color: theme.colors.text },
  navGroup: { flexDirection: "row", gap: 10 },
  navIcon: { padding: 8, backgroundColor: theme.colors.background, borderRadius: 12 },
  dateBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 15,
  },
  dateCard: {
    alignItems: "center",
    paddingVertical: 12,
    width: 62,
    borderRadius: 20,
    backgroundColor: theme.colors.background,
  },
  dateCardActive: { backgroundColor: theme.colors.text },
  dateDay: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginBottom: 4,
    fontWeight: "600",
  },
  dateNum: { fontSize: 17, fontWeight: "800", color: theme.colors.text },
  activeDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#FFF",
    marginTop: 3,
  },
  textWhite: { color: "#FFF" },
  scrollContent: { padding: 20, paddingBottom: 40 },
  classItem: { flexDirection: "row", marginBottom: 20 },
  timeSide: { width: 55, alignItems: "center", paddingVertical: 4 },
  startTime: { fontSize: 14, fontWeight: "800", color: theme.colors.text },
  endTime: { fontSize: 11, color: theme.colors.textSecondary, fontWeight: "600" },
  verticalLine: {
    width: 2,
    flex: 1,
    marginVertical: 6,
    borderRadius: 1,
    opacity: 0.4,
  },
  mainCard: {
    flex: 1,
    backgroundColor: theme.colors.card,
    borderRadius: 22,
    padding: 16,
    marginLeft: 12,
    borderLeftWidth: 5,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  classTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: theme.colors.text,
    marginBottom: 2,
  },
  batchSubText: { fontSize: 12, color: theme.colors.textSecondary, fontWeight: "500" },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  statusText: { fontSize: 10, fontWeight: "800" },
  cardFooter: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingTop: 12,
    alignItems: "center",
  },
  infoRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  infoText: { fontSize: 12, color: theme.colors.text, fontWeight: "500" },
  emptyContainer: { alignItems: "center", marginTop: 80 },
  emptyIconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  emptySubText: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    textAlign: "center",
    paddingHorizontal: 40,
  },
  loadingContainer: {
    alignItems: "center",
    marginTop: 100,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 14,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
}));
